### ISSUE TITLE
Select field option to mark all for removal

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#101]
Would it be possible that in the "select" field all options could be eliminated at once?
This would be useful when there are many options in the selector.
Thank you

**Comment by michaelpollak** [comment]
Good morning,
can you give us some more information about your needs? I assume you are talking about the frontend user interface and the field "Select (mutliple)"? Do you render as autocomplete?

**Comment by jesusman111** [comment]
Good morning
When there are many items in the selector field and you want to delete all
at once to interfere others, it is a very long task.
I would like that in the edit menu of the selector field all items could be
marked and deleted at once.
Thank you very much for your attention

**Comment by jesusman111** [comment]
I have another one issue. Do you know when datalynx will come out for
moodle 3.8?
Thanks again

**Comment by michaelpollak** [comment]
That's an interesting idea, I see your point. 
Wouldn't it in your case not be easier to just add another field to the instance and start from scratch?
If you remove every single option from select you end up with an empty definition, a case we currently catch with an error message. A select all option could be implemented with JS, I have to work on two urgent tasks and will look into this feature some more after that.

Thanks for your input.

**Comment by michaelpollak** [comment]
Concerning the supported Versions, we are testing on 3.8 already and there are no known problems. Of course we would appreciate some manual testing if you have the chance to do so. 
Automated testing is done from 3.5 up to and including 3.8 (https://travis-ci.org/michaelpollak/moodle-mod_datalynx).

**Comment by jesusman111** [comment]
That is the option I am currently using, but the problem is that if the
field is used in the filters it cannot be deleted directly.

Another problem that I have detected in this same field is that when words
have an accent, as in Spanish, they are not arranged correctly in
alphabetical form.

Thank you very much for your answers

**Comment by michaelpollak** [comment]
I became curious and found this function to select all options for deletion. Can't promise David will push this to the next release but the patch is easily upgraded if you need this more often. See my commit https://github.com/michaelpollak/moodle-mod_datalynx/commit/7e2f4306bd5bd7e3b491775d79896d7a594d65a9

![grafik](https://user-images.githubusercontent.com/475798/75175126-090c3e00-5732-11ea-9743-898001da1469.png)

It adds a link below the submit buttons to select all options for deletion at once. Remember that you cannot save this without adding at least one option.

_Concerning your problems with accents, could you open a new issue, it's very hard to keep track of combined reports. Thank you, greetings from Austria!_

**Comment by jesusman111** [comment]
I have already opened a new issue

Thank you so much for everything

**Comment by jesusman111** [comment]
Approximately, do you know when the next version will be released?

Very thankful

**Comment by michaelpollak** [comment]
Sadly I can't give you any info on that, but our project lead David may
share some insight when he stumbles upon this :)
If you are aware of the risks you can always work with the develop branch
of this plugin, depending on your use case. You can reach me directly per
mail for further questions, have an interesting day.

Am Mo., 24. Feb. 2020 um 18:36 Uhr schrieb jesusman111 <
notifications@github.com>:

**Comment by jesusman111** [comment]
Thank you so much for everything
