### ISSUE TITLE
Entries pending approval

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#116]
Hi,
The activity summary module does not reflect entries pending approval, which is a requirement.
Regards
![img-10](https://user-images.githubusercontent.com/61394948/76359309-49b3ac00-631b-11ea-9ff5-680ed70c0f1a.png)

**Comment by dasistwas** [comment]
Sorry, but what is the "activity summary module"? Could you add some explanation?

**Comment by jesusman111** [comment]
It is a native block of moodle, in which the activities of the course are related.
This problem occurs in all versions of moodle in which I have tried (3.5-3.8).
I enclose screenshots.
Regards

![img-11](https://user-images.githubusercontent.com/61394948/76413238-5ecd2100-6395-11ea-8e96-b7e2e5cf8181.png)
![img-12](https://user-images.githubusercontent.com/61394948/76413244-612f7b00-6395-11ea-8020-a67f4cabfc74.png)

**Comment by michaelpollak** [comment]
Well I really tried but was not able to find an "activity summary module" or something along these lines in either mdl 35 or 38, can you point me in the right direction? Where do you find this report (I assume?), thanks for clarifying. I will look into it.

**Comment by jesusman111** [comment]
Do you need any further clarification?
I am at your service

**Comment by michaelpollak** [comment]
Yes in this case I am quite lost, can you explain where you click in order to get to the site in the screenshot. Maybe show us the URL as well, I'm curious how to find this "summary module". Thank you.

**Comment by jesusman111** [comment]
The module is called "Activities block" and is native to moodle.
I include screenshot of the module and its configuration.
I remain at your disposal for what you need.

![cap-1](https://user-images.githubusercontent.com/61394948/76954509-bed14380-6910-11ea-96c0-96cfb80b53d2.png)
![cap-2](https://user-images.githubusercontent.com/61394948/76954516-c09b0700-6910-11ea-84da-f25955f09a48.png)
![cap-3](https://user-images.githubusercontent.com/61394948/76954523-c264ca80-6910-11ea-9e47-27d6b744e01b.png)

**Comment by jesusman111** [comment]
In the moodle database module, the number of entries that are pending approval are shown in the "pending" column, while in datalynx it always appears "---"
You can ask me how much you need.
![cap-4](https://user-images.githubusercontent.com/61394948/76954907-75cdbf00-6911-11ea-974f-b2e2ea09bb7e.png)

**Comment by jesusman111** [comment]
Attached screenshot of the module in "Plugins overview"
I hope it helps you.

![cap-5](https://user-images.githubusercontent.com/61394948/76955686-ec1ef100-6912-11ea-8465-cffb0ba1b18a.png)

**Comment by michaelpollak** [comment]
Thank you! :)
Now I was able to see what you mean, for future reference you see _mod/datalynx/index.php?id=2_ where 2 is the courseid. Have never considered this, I will look into it and get back to you. Thank you for your time.

**Comment by jesusman111** [comment]
Thanks to you
I will be waiting in case you need anything else.

**Comment by michaelpollak** [comment]
Thanks to your feedback this feature will be available with the next release of datalynx, the line above this comment shows the update I just finished. Great work!

**Comment by jesusman111** [comment]
Great! Thank you
Do you know when the next version will come out?

**Comment by michaelpollak** [comment]
Give it a week or two, we are trying to cluster features for every release. 
If you need a quicker turnaround you can always try a beta release or patching by hand until the update is out.

**Comment by jesusman111** [comment]
Ok.
There is another pending bug (# 108)
Have you been able to analyze it?
Thank you very much again

**Comment by michaelpollak** [comment]
Not yet, sorry, we have limited funds for this project.

**Comment by jesusman111** [comment]
Received thanks
If you need any clarification in this regard, I am at your disposal.
See you soon

**Comment by dasistwas** [comment]
Now "Pending" shows all entries approved or not.

**Comment by michaelpollak** [comment]
Hey David,
thanks for the feedback. I don't see what you describe but maybe I got this somehow wrong.
I have a few testcases, one has 15 entries and I approved three, this shows 15 and 12 pending in the overview. When we have not approved any entry it shows the same number.

**Comment by dasistwas** [comment]
Hi @michaelpollak,
thank you for the quick reply: I did some bugfixes, please merge with my branch. Also concerning pending: When the setting for  "Require approval" is not set, then pending is equal to the number of entries which is misleading. I did not test with "Require approval" enabled.

**Comment by michaelpollak** [comment]
Ah now I see what you mean, in case approval is not enabled we show --- for pending to make it visible. Thanks for pointing that out. 
![grafik](https://user-images.githubusercontent.com/475798/78134188-0501c900-7420-11ea-953f-f67f3cb5e00b.png)

**Comment by dasistwas** [comment]
I think this is fixed. Great work.
