### ISSUE TITLE
Adjust behavior language strings to clarify.

### ISSUE THREAD

**Issue by michaelpollak** [Wunderbyte-GmbH/moodle-mod_datalynx#120]
Copied this from here: https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/issues/119

---
When you go to Manage -> Edit View then you have the form with the view settings. On top of the form you have the setting "Visible to": Then you have these choices:

    manager
    teacher
    student
    guest

But these choices are labelled the wrong way. They should have the following label:

    Users with the view privilege "manager" usually assigned to managers
    Users with the view privilege "teacher" usually assigned to teachers
    Users with the view privilege "student" usually assigned to students
    Users with the view privilege "guest" usually assigned to guests or authenticated users
---

Fix these labels and write useable helptext.

**Comment by dasistwas** [comment]
Could be improved even more, but for now I will close that. Thank you for clarifying this usability issue.
