### ISSUE TITLE
Error adding fields in csv view #117 (Closed)

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#121]
I think that while field functionality is fixed, it is best to display it.
Could it be left as it was? (show field).
Thank you

**Comment by jesusman111** [comment]
After using it I have realized that it is better to have the dropdown as a reference, even if it is not included when clicking on it.
Could it be left as it was?
Thank you
![cap-8](https://user-images.githubusercontent.com/61394948/81557180-d5819d00-938b-11ea-8369-4248f3b20df0.png)

**Comment by michaelpollak** [comment]
I will propose a list of fields that can be displayed for reference like that:
![grafik](https://user-images.githubusercontent.com/475798/81560310-70c94100-9391-11ea-8d16-e69b77bbeeca.png)

**Comment by jesusman111** [comment]
Ok. Very good.
Thank you

**Comment by dasistwas** [comment]
Great improvement. Thank you.
