### ISSUE TITLE
Datalynx and editing in moodle

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#123]
When editing in moodle is activated and Datalynx is used, it is deactivated.
Could datalynx respect moodle edit on / off status?

Thank you so much for everything

**Comment by michaelpollak** [comment]
That was a great catch, this bug actually went unnoticed for seven years! 
Tracked down and fixed it, will be online with the next datalynx release. Have a nice day and thank you for your feedback.

**Comment by dasistwas** [comment]
Never noticed that bug. Though using datalynx a lot ;). Thank you for fixing.
