### ISSUE TITLE
Failed to sort alphabetically with filters

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#124]
When I use filters, alphabetical sorting is not done correctly.
Attached screenshots
Thank you
![cap-1](https://user-images.githubusercontent.com/61394948/81479877-77877500-9226-11ea-87a1-4c0f4f7bb5e7.png)
![cap-2](https://user-images.githubusercontent.com/61394948/81479882-7bb39280-9226-11ea-8f2b-090fb50374ad.png)

**Comment by michaelpollak** [comment]
Without knowing what "Tipo" and "Fecha" means I have recreated your setup and can't reproduce at the moment. 
![grafik](https://user-images.githubusercontent.com/475798/81556198-37d99e00-938a-11ea-9071-816d807ba32b.png)

Grouping and sorting works as expected, can you please send more information and/or a backup of your datalynx instance so I can learn more about it. Thanks.

**Comment by jesusman111** [comment]
I enclose the backup

[copia_de_seguridad-moodle2-activity-319-datalynx319-20200511-1328.zip](https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/files/4609230/copia_de_seguridad-moodle2-activity-319-datalynx319-20200511-1328.zip)

**Comment by michaelpollak** [comment]
Can reproduce, your "Tipo" is a select field and sorting alphabetically does not work. Tracking down the source of this right now.

**Comment by dasistwas** [comment]
Thank you for reporting and fixing this!
