### ISSUE TITLE
Links of the URL type fields

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#125]
What do I have to do to make the links of the URL type fields active?
Thanks again

![cap-3](https://user-images.githubusercontent.com/61394948/81481489-dd78fa00-9230-11ea-91de-7728a1a39dff.png)

**Comment by jesusman111** [comment]
Filters are activated.
I use moodle 3.8
Thank you

**Comment by michaelpollak** [comment]
Hello and thanks for the feedback. This is a little hidden feature, you can make the urls clickable by rendering them as :link. Follow these steps:

1: Go to the view
2: Show advanced buttons
![grafik](https://user-images.githubusercontent.com/475798/81483791-2173fb00-9241-11ea-8972-1e8188d0e77b.png)
3: Show html 
![grafik](https://user-images.githubusercontent.com/475798/81483825-423c5080-9241-11ea-8eec-93567d43688b.png)
4: Find your url field, in my testcase it is named testurl and you can find [[testurl]] in the html code.
5: Add specific renderer like this: [[testurl:link]]
6: Save your changes, your links are clickable now!

Let me know if this helps in your organisation, and thank you for your feedback. I will petition to get this added to the usual "Field tags" dropdown menu to make it easier.

**Comment by jesusman111** [comment]
It gives me the following error

![cap-5](https://user-images.githubusercontent.com/61394948/81484445-cbee1d00-9245-11ea-8e49-cf51e2cc92e7.png)
![cap-4](https://user-images.githubusercontent.com/61394948/81484446-ce507700-9245-11ea-991a-962859bb5742.png)

Thanks you

**Comment by michaelpollak** [comment]
Please check without the space infront of the doublepoint

**Comment by michaelpollak** [comment]
Tested an can reproduce, please don't use | in your fieldnames.

**Comment by jesusman111** [comment]
It does not work
Sorry

![cap-6](https://user-images.githubusercontent.com/61394948/81485564-27240d80-924e-11ea-9205-92596b06b70f.png)
![cap-7](https://user-images.githubusercontent.com/61394948/81485565-28edd100-924e-11ea-8287-0629ded77e38.png)

**Comment by michaelpollak** [comment]
Ok just to be sure please check those steps.
Go to "Fields" and check if your url field is named "Enlace"
The settings in the view seems correct, I tested with the fieldname "Enlace" and it works perfectly fine.
![grafik](https://user-images.githubusercontent.com/475798/81485752-d6151900-924f-11ea-830b-f545aba1f9c5.png)

**Comment by jesusman111** [comment]
Sure enough, there was an error in the field name.
Sorry!
Thanks again

**Comment by michaelpollak** [comment]
I'd argue this is a valid issue and we may show the :link renderer in the select list for url fields.

**Comment by jesusman111** [comment]
Ok
Thanks again.

**Comment by dasistwas** [comment]
Thank you  for adressing this issue.
