### ISSUE TITLE
Problem with configurable reports and datalynx

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#126]
I am using the plugin "configurable reports"
When I include a query from a datalynx module, the word "qualification" is always displayed, even if the module is not qualifiable.
Greetings and thanks

![cap-11](https://user-images.githubusercontent.com/61394948/81683616-93715d80-9456-11ea-95f3-5b28d80386be.png)
![cap-10](https://user-images.githubusercontent.com/61394948/81683625-94a28a80-9456-11ea-8cff-23f1a53f7b38.png)

**Comment by dasistwas** [comment]
Hi,
sorry we do not answer support questions for other plugins.
Kind regars,
David
