### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#136]
I have been testing the datalynx notifications and have not found them to work.

I guess they should reach me by email.

I use moodle 3.8.
Other notifications from moodle if they reach me correctly.

I have tried different configurations and I have not been able to receive them.

Is it possible that you are doing something incorrectly?

Thanks for everything

**Comment by michaelpollak** [comment]
I have not built this functionality but my initial tests just now were okay. We utilise the moodle Task API and hand over messages that should be send to moodle core. Tested with 3.6 and 3.8 right now and seems to work as expected.

Please try to set up the following case:

- Go to "Rules -> Event notifications"
- Enter a name and tick the "Enabled" checkbox
- Select "Entry created" and "Entry updated" as trigger events
- Select to "Author" and save this notification.

Now Create an entry. You should receive a notification via mail if your user has an email set up.

If this is not the case, please check your SMTP server log and get back to us. It's always possible that some weird bug hides behind a rock. Thank you for your feedback.

**Comment by jesusman111** [comment]
I want the notification to be sent when a comment is created.

Is that possible?

Thank you, Michael

**Comment by michaelpollak** [comment]
Sure this is one of the features, just for testing I would recommend you try if notifications reach you when you create an entry. Sorry if I was not clear enough.

The troubleshooting process always simplifies a task and checks, if simple works we try more complex setups and ultimately everything should work :)

**Comment by jesusman111** [comment]
Hello again Michael:

Following the steps you have indicated has worked.

Now how can I make notifications work with comment creation?

Thanks a lot for everything
Jesus

**Comment by michaelpollak** [comment]
Try to check and if necessary extend the permissions of your user. 
To be notified when a comment is added we use the "**notifycommentadded**" privilege.

You can check if your user has this privilege activated under **Site administration -> users -> Permissions -> Check permissions**. 

Per default teachers do have this privilege, you may be right this default could be rethought. Can you confirm that your user has this permission and still does not receive mail after commenting. Thank you.

**Comment by jesusman111** [comment]
The permissions are correct.

 I don't quite understand the datalynx comment notification setup options. Could you explain it to me briefly? (it is possible that something is wrongly configured) 

Thank you very much for your help.

**Comment by jesusman111** [comment]
I have made the notifications work for me correctly.
I think it would be very interesting to update the documentation of the application.
Thanks again

**Comment by michaelpollak** [comment]
I agree fully :) Great you got it to work.
My priorities currently are on urgent fixes and the mobile implementation, but documentation is certainly needed. I have started it but David and I only have so much resources to work on datalynx.

Can you please explain what your misunderstanding was and how you got this to work. I would like to add it to the documentation.

Thank you for your feedback, have a good start in the new week :+1:

**Comment by dasistwas** [comment]
@jesusman111 It would be great, that you can provide your knowledge for the community. You can add the things you learned directly to the official documentation:
https://docs.moodle.org/39/en/Datalynx_module
So we can focus on the programming part and continue to support you when there is any question or bug to fix.

**Comment by jesusman111** [comment]
What I have done has been to follow the directions of David Bogner.

I have renamed the roles and have been able to use 4 different ways of notification.
You guys are doing a great job.

Thank you very much

**Comment by michaelpollak** [comment]
Closing this as that issue is resolved. Thanks again for your input.
