### ISSUE TITLE
User images. Export pdf

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#137]
Hello:

When exporting to pdf, users profile images are not displayed.

Attached document.

I wish you happy holidays.

A cordial greeting

[pictures.pdf](https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/files/5086028/pictures.pdf)

**Comment by michaelpollak** [comment]
Thank you for the report, I have tested this issue and can't confirm. Profile pictures are exported, tested with author:picture as well as author:picturelarge. Are you sure the profile pictures are available, can you see them in the view?

**Comment by jesusman111** [comment]
Hello again:

The images look good on the screen but not in pdf.

Attached screenshots.

Thanks for everythin

![img1](https://user-images.githubusercontent.com/61394948/91048838-88fd5d00-e61c-11ea-9da3-2a71b7f550a6.png)
[img2.pdf](https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/files/5117998/img2.pdf)

**Comment by michaelpollak** [comment]
Have tested with a few different setups on mdl3.5 and mdl3.8, no problems with the tools as far as I can see.
Any special setup in your datalynx? I'd like to help you out, but at the moment I can't reproduce this behavior.

**Comment by jesusman111** [comment]
I am attaching a backup copy.
I hope this helps.
Thanks again
[copia_de_seguridad-moodle2-activity-626-datalynx626-20200825-1112-nu.zip](https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/files/5122668/copia_de_seguridad-moodle2-activity-626-datalynx626-20200825-1112-nu.zip)

**Comment by michaelpollak** [comment]
User images are not exported bc. of privacy settings. With a temporary account I could track down the issue - possibly a strange file format or some other minor detail - but at the moment we try to finish the mobile implementation for datalynx.
Hope this helps for now and thank you for your interest in our work! :)
