### ISSUE TITLE
 Problems with translation of dates.

### ISSUE THREAD

**Issue by jesusman111** [Wunderbyte-GmbH/moodle-mod_datalynx#142]
Hello:
I can't get the dates to translate. The rest is translated, but the name of the months is not.

How could I fix it?

Thank you very much
Jesus

**Comment by michaelpollak** [comment]
Hello, good to hear from you.
Can you explain where you see the missing language strings, thank you.

**Comment by jesusman111** [comment]
I use the Spanish language and everything appears in this language except the dates that come out in English.
Attachment screenshot.

Thanks a lot for everything
![cap-fechas](https://user-images.githubusercontent.com/61394948/96291475-5d796c00-0fe8-11eb-8919-5ae99cbcee4f.png)

**Comment by michaelpollak** [comment]
My quick check confirmed your report.
I found this note in the docs, can you tell me if your operating system is set to Spanish or by chance to English?

https://docs.moodle.org/39/en/Calendar_FAQ#Why_are_month_names_not_being_displayed_in_the_correct_language.3F

I agree that this is bad design by moodle itself, it is discussed in this bug report: https://tracker.moodle.org/browse/MDL-50364

**Comment by jesusman111** [comment]
I use windows 7 and it is configured in Spanish.

Thanks again

**Comment by michaelpollak** [comment]
We sadly can't do much about that, it is a known Moodle core bug.
If you absolutely need a patch let me know and I will look into fixing this in the core files either as a patch or upstream fix.

**Comment by jesusman111** [comment]
The strangest thing is that I have another moodle, with the same version and on the same server and it works correctly.
If the solution were simple, it would be very good for me.

![cap-fechas2](https://user-images.githubusercontent.com/61394948/96304819-1b0e5a00-0ffd-11eb-9222-cfe040b40c45.png)

Thanks again

**Comment by michaelpollak** [comment]
This is curious, can you by chance compare the language settings of these two instances?
Site administration -> Language -> Language settings

**Comment by jesusman111** [comment]
I have compared the language settings and many other things and they are the same.
So is the config.php file

It seems that it has to be something from moodle, but in this case it affects one yes and the other not.

See you soon
