### ISSUE TITLE
CSS / JS Cache is buggy

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#145]
There is a problem with the integration of CSS/JS used in the "Manage" tabs of the datalynx activity.

Example content of JS tab

```
require(['jquery', 'theme_bootstrapbase/bootstrap'], function($) {

$('.bar-success').each(function(){
    var successvalue = $(this).text();
    $(this).attr( "style", "width: " + successvalue);
});

$('input[name^=field]').click(function() {
        if($(this).attr('checked') == 'checked'){
            $(this).attr('checked', false)
        } else {
            $(this).attr('checked', true);
        }
        //$(this).attr('previousValue', $(this).attr('checked'));
});

});
```
Problem: When I change the JS then it is not reflected when I add or edit an entry. Same thing with CSS. 

Caching of CSS and JS should be cleared when I purge caches (theme and or JS). 

It is a little bit difficult to reproduce, here a screenshot of JS in the inspector

![js-in-datalynx](https://user-images.githubusercontent.com/1620975/101803050-65e5b300-3b10-11eb-9000-99a42c092f95.png)

**Comment by michaelpollak** [comment]
Good morning,
this is interesting, I have never noticed that behavior. Will try to reproduce and isolate now.

**Comment by michaelpollak** [comment]
Steps:
I check and activate cachejs
I go to manage -> JS
In the field Javascript code I enter `alert("testing");`
I open a view and see the alert
I remove the alert from the field Javascript Code
I reload the view and see no alert

Tested on mdl35 and mdl38. I will try to reproduce your exact example. To me this feels like a minimal viable test, do you use any caching plugins or special settings?

**Comment by michaelpollak** [comment]
Tried with minimal CSS code too
```
.addnewentry {
  color: red;
  font-weight: bold;
}
```

Also no caching, changes are gone as soon as I remove it from Manage -> CSS

**Comment by dasistwas** [comment]
using M3.9

**Comment by dasistwas** [comment]
try to use chrome and change the content multiple times

**Comment by michaelpollak** [comment]
Tested with 3.9 as well but may be a browser bug, I used Firefox. Will try multiple browser and multiple changes.
Javascript is loaded everytime the view is reloaded, so should - in theory - not be cached. Thanks for the pointers.

**Comment by michaelpollak** [comment]
No luck for now, browsers don't change the outcome. Will try different OS next just to be sure but from my perspective this is not cached.

**Comment by winnidat** [comment]
https://drive.google.com/file/d/1m9TzQhrFgnzmGQJ4XeYhXHGPzDBG1XQ2/view
That is the output i get. It only works after clearing site data
![image](https://user-images.githubusercontent.com/26013011/101900373-a6e0d480-3baf-11eb-8a6a-b47dd7bf3812.png)

**Comment by michaelpollak** [comment]
Any chance you can give me a temporary account on m39.wunderbyte.at, I can't reproduce it on my servers. 
May be specific to the configuration of this server / moodle / instance / ...

**Comment by michaelpollak** [comment]
Ah, I found the problem, working on it.
I can see it only if I check the generated code without updating anything. Will look into it now and hopefully post a patch soon. Here ".../moodle39/mod/datalynx/css.php?d=1" shows the cached stylesheet because we keep it for 600 seconds.

**Comment by michaelpollak** [comment]
We can just set the expiraton for generated css and js to 0, it currently is set to 600 seconds. Is this a solution to your problem?

**Comment by winnidat** [comment]
i hope ;-)

**Comment by winnidat** [comment]
Looks good! 
Thanks and have a nice weekend

**Comment by winnidat** [comment]
ok seems it only worked once and the same issue still persists

**Comment by dasistwas** [comment]
@michaelpollak ther must have been some changes in core concerning delivering CSS/JS. Problems only startet with M3.9 or M3.8. Could you look at mod/data, how it is done there?

**Comment by michaelpollak** [comment]
Good morning David,
thanks for the feedback. The plugin mod/data does the same thing, it's basically identical, and sets expiration of the files to 600 seconds / 10 minutes.
Do you experience problems with css or js right now? Did you update both files (css.php and js.php), I pushed js.php only after you checked it out. The file js.php:141 should say `$lifetime = 0;`

Please confirm that css.php:134 says `$lifetime = 0;` and that you see CSS caching - as I can't explain this behavior right now. If so I can narrow the bug down and work on this CSS caching first.

Thank you :)

**Comment by dasistwas** [comment]
New test results:

- JS and CSS works fine editing existing entries
- Does not work adding new entry
- Problems only on nachqualifizierung.at
- Maybe upgrade problem with data in DB?
- @michaelpollak created account for you

**Comment by dasistwas** [comment]
Laden fehlgeschlagen für das <script> mit der Quelle "https://www.nachqualifizierung.at/lib/requirejs.php/-1/core/drawer_events.js".

**Comment by dasistwas** [comment]
```
Uncaught Error: Script error for "core/drawer_events", needed by: core/drawer
http://requirejs.org/docs/errors.html#scripterror
    makeError https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:168
    onScriptError https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1738
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1943
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1685
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:834
    fetch https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:824
    check https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:856
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1176
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1557
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1161
    bind https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:134
    each https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:59
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1113
    init https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:788
    callGetModule https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1203
    completeLoad https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1590
    onScriptLoad https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1717
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1942
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1685
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:834
    fetch https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:824
    check https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:856
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1176
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1557
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1161
    bind https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:134
    each https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:59
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1113
    init https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:788
    callGetModule https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1203
    completeLoad https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1590
    onScriptLoad https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1717
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1942
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1685
    load https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:834
    fetch https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:824
    check https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:856
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1176
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1557
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1161
    bind https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:134
    each https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:59
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1113
    init https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:788
    localRequire https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1460
    setTimeout handler*req.nextTick< https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1815
    localRequire https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1449
    requirejs https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1797
    <anonymous> https://www.nachqualifizierung.at/mod/datalynx/view.php?d=5&view=9&filter=10&editentries=15596&sesskey=JFPxPwxDU9&sourceview=9&eids=15596:10350
    execCb https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1696
    check https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:883
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1139
    bind https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:134
    emit https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1189
    each https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:59
    emit https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1188
    check https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:938
    enable https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1139
    bind https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:134
    emit https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1189
    each https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:59
    emit https://www.nachqualifizierung.at/lib/javascript.php/-1/lib/requirejs/require.js:1188
```

**Comment by dasistwas** [comment]
```
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://www.nachqualifizierung.at/lib/requirejs.php/-1/core_message/message_drawer_view_settings.js
Source-Map-Adresse: https://www.nachqualifizierung.at/lib/jssourcemap.php/core_message/message_drawer_view_settings.js
```

**Comment by dasistwas** [comment]
@winnidat most recent version was not checked out. branch was in detached head state

**Comment by dasistwas** [comment]
CSS not loaded:
https://www.nachqualifizierung.at/mod/datalynx/view.php?d=3&view=5

**Comment by dasistwas** [comment]
www.nachqualifizierung.at 0 185.17.13.127 - - [16/Dec/2020:01:38:49 +0100] "GET /theme/font.php/campus/theme/1608063898/SourceSansPro-Semibold.woff HTTP/2.0" 500 32768 "https://www.nachqualifizierung.at/theme/styles.php/campus/1608063898_1608065364/all" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"

**Comment by dasistwas** [comment]
`www.nachqualifizierung.at 0 185.17.13.127 - - [16/Dec/2020:01:47:44 +0100] "GET /theme/font.php/campus/theme/1608063898/SourceSansPro-Black.woff HTTP/2.0" 500 32768 "https://www.nachqualifizierung.at/theme/styles.php/campus/1608063898_1608065364/all" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"`

**Comment by dasistwas** [comment]
`www.nachqualifizierung.at 0 185.17.13.127 - - [16/Dec/2020:02:14:29 +0100] "GET /theme/styles.php/campus/1608080593_1608080724/all HTTP/2.0" 500 32768 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"`

**Comment by dasistwas** [comment]
@winnidat @michaelpollak Any news? When I add a new entry, the problem still exists when I add a new entry. I added an account for @michaelpollak on nachqualifizierung.at

https://www.nachqualifizierung.at/mod/datalynx/view.php?d=3&view=5

Click on "Eintrag hinzufügen"

After saving the entry and waiting for a day, the JS/CSS starts to work.

**Comment by dasistwas** [comment]
The JS and CSS is just not loaded.

![not-loaded](https://user-images.githubusercontent.com/1620975/102424612-d35f7b00-400b-11eb-816e-e52a15e3b798.png)

**Comment by michaelpollak** [comment]
Good morning :)
I had no time to look at it yesterday. Thanks for the inputs and the login, I don't have admin privileges but at least I can see the situation now. The css.php is actually included, you can see the CSS in "Stilbearbeitung". Looks good to me, form reacts to changes and all.
The js.php is included and you can see it in the debugger window. The code throws errors, will look into that now. Trying to rebuild on my testservers.

**Comment by michaelpollak** [comment]
Tracked down your problem,
in moodle35 the form id is always "mform1" but in m39 forms have an identified attached, like "mform1_XmDU9LaHgUJdpxa". Your javascript looks for #mform1, does not find it and throws an error. Simple fix is to look for the class, which in this case is simply .mform .

I advise to update your JS code on line 242 from
`Y.one('#mform1').on('submit', function(){`
to
`Y.one('.mform').on('submit', function(){`

Not sure about other bugs in the code as it's tough to reproduce this complex form. But it's a step.

**Comment by michaelpollak** [comment]
@dasistwas bitte kurz testen ob sonst noch Fehler auftauchen oder das dieses Issue fixed, danke :)

**Comment by dasistwas** [comment]
Hallo @michaelpollak super, Danke für das Finden des Form-Problems.

Es gibt noch ein Szenario, das nicht funktioniert:

1) Eintrag hinzufügen
2) Speichern.
3) Erneut bearbeiten
4) Speichern
5) Eintrag Löschen
6) Eintrag hinzufügen -> JS wird nicht geladen.

**Comment by winnidat** [comment]
Vielleicht liegt der Fehler im classes/datalynx.php ab Zeile 539 - denke hier wird die Datei geladen.

**Comment by winnidat** [comment]
Also wenn ich 578 und 538 auf True setze wird immer beides geladen. Anscheinend fehlt hier irgendwo der $params->css bzw. js Wert.

**Comment by michaelpollak** [comment]
I've tested this now also with a few rounds of "create, edit, delete, create" and don't see a problem anymore. 
Firefox "Debugger" does sometimes not show the file, I see that too, but when I look at "Netzwerkanalyse" it is clearly loaded. Checked the same with Chromium, here the js.php file is always shown and has correct content.

Can you explain where you see what bugs?

It s a smart idea @winnidat but I don't think that is our bug. $params->js defaults to true and is not changed in the URL. Nice to see some more people working on this! :+1:

**Comment by winnidat** [comment]
i ve changed it on the nachqualifizierungsserver so maybe thats why it is working (or are you testing locally)? And param->css was Null after the delete -> new sequence.

**Comment by michaelpollak** [comment]
Ah okay, that makes sense. Can't reproduce locally so I tested on nachqualifizierung. 
Will look at the code why params->css might be null over there, thanks for the quick feedback.

**Comment by dasistwas** [comment]
now it works. the steps above to reproduce are now working fine. congrats! awesome job. If we could get that in the datalynx module core code, that would be great as well @michaelpollak @winnidat

**Comment by winnidat** [comment]
Ok so i will leave if (true)  instead of (!empty($params->css)) in the nachquali code as a work around but maybe you can find the root of the problem.

**Comment by michaelpollak** [comment]
I do agree, better to find the bug. And I did finally, see my commit, when we are in edit mode we call a yui module with some parameters. Problem is, the variable name is $params and overwrites our urlparams that have css and js information inside!

Tiny tiny oversight, thanks @winnidat for the pointer with css=null

**Comment by dasistwas** [comment]
Great job @michaelpollak @winnidat. Huge step towards Christmas!
