### ISSUE TITLE
Fix problem with fieldtype datalynxview

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#146]
When adding fieldtype with datalynxview, then in single view (eids in url) the field is not shown. in list view it is shown. Filter in field settings "author" should match.

**Comment by dasistwas** [comment]
Good to fix this week. we upgrade next week. Thank you!

**Comment by michaelpollak** [comment]
Good morning David.
Do you have a link for this behaviour, I can't reproduce it here so I assume some setting in nachqualifizierung may cause the issue.

**Comment by dasistwas** [comment]
Problem gelöst: Es handelte sich um 2 unterschiedliche Nutzeraccounts, aber um die selbe Person. Diese hat nicht gemerkt, dass sie 2 Accounts hat.
