### ISSUE TITLE
Add YoutubeField Type

### ISSUE THREAD

**Issue by winnidat** [Wunderbyte-GmbH/moodle-mod_datalynx#152]
Output should be an iframe with youtube src.

- setting for width and height in percent and px
- either use normal youtube link with moodle filter or embed link

**Comment by michaelpollak** [comment]
Great idea, implemented and currently testing.
The teacher can set a width and height, students parse Youtube URL and the view shows all posted videos.

**Comment by michaelpollak** [comment]
Currently only storing the Youtube video ID,
checking if the URL is valid, what other kind of checks should we perform on the input side?

**Comment by winnidat** [comment]
hmm i dont know :-). Maybe it is enough

**Comment by winnidat** [comment]
Can I test it?

**Comment by michaelpollak** [comment]
Yes, looking forward to your feedback. :+1:

**Comment by winnidat** [comment]
Looks perfect 👍 .
I just need 2 other adjustments.

1.  possibility so that normal uploaded video files also show as videos and not as download (maybe implement in picture field with add file extensions) like the video upload icon in a texteditor 

2. implement the code from this branch (https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/tree/dev-gem - Show default view in course list
)
  with an admin setting to enable and a datalynx setting to set the specific view

Thanks in advance. If possible can you implement it till thursday?

Best, Thomas

**Comment by dasistwas** [comment]
do not implement https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/tree/dev-gem that code is buggy. use datalynxcoursepage instead for that purpose

**Comment by michaelpollak** [comment]
I looked into this and will extend the picture field to embed video files. This will be a pretty much hidden feature, if it is important to some usecases it might be smarter to add a specific video field type.
To avoid feature creep and an unusable interface structure we could implement a "field type chooser" for the admins, to select which field types are visible to the datalynx managers and which are hidden from the UI.

**Comment by winnidat** [comment]
Yeah a specific video field type would be good. Maybe we can also use the youtube field type and call it video field with the options of the link or a video file.

**Comment by michaelpollak** [comment]
Draft of extended picture field is finished, testing now.

**Comment by dasistwas** [comment]
Concerning video upload: That could either be an extra field with the appropriate settings to display a video (derived from picture upload or file upload). Mixing picture with video does not some quite OK, because settings might be different. Also the text editor has the possibility to integrate video files. 
Youtube could have another option like vimeo. But for the beginning just youtube is OK.

**Comment by michaelpollak** [comment]
It sounds strange, I agree, but it is not as bad. Testing went well, but it's kind of a hidden feature. I added a selector to allow video files, sizing information is used as well, and a simple video tag embeds the file.
![grafik](https://user-images.githubusercontent.com/475798/108060619-64c48b00-7057-11eb-82c2-48d01d31459e.png)

So I guess my question is, do we need (and want) an extra field type, extending the long field type selector some more? I am not sure - as this is marked urgent - what and how to implement ultimately. Thanks for clarifying.

**Comment by michaelpollak** [comment]
I propose to rename the field type picture in the frontend to "**Pictures and Multimedia**" to allow images, videos and audio to be uploaded. Selection is made by the selected accepted file types, in the renderer determine if an img, video or audio tag is added.
This approach keeps current functionality and backwards compatibility while adding a field type to use with video and audio embeds.

Draft of this implementation in the current commit.

**Comment by michaelpollak** [comment]
Added a new Issue as I think the youtube embed is done. I agree that a vimeo option would be nice, but we can implement this once it is an actual user requirement. 
If youtube field type is done please close this :) Thanks for all your feedback.

**Comment by winnidat** [comment]
Hi Michael, just one bug mp4 Video is shown as Audio 
![image](https://user-images.githubusercontent.com/26013011/108561139-05d46f80-72fe-11eb-8450-48c240e17d3b.png)

Best,
Thomas

**Comment by michaelpollak** [comment]
The multimedia field type is not completed yet, I want to update the field settings dialogue. Still some untested code and debug stuff in there, I fixed the "all media is audio" bug you saw, used to check the audio playback.
Can you please use the issue https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/issues/156 to discuss and feedback multimedia field, will make things easier to follow and backtrack in the future. Thank you :+1: 

Have a nice weekend :100:
