### ISSUE TITLE
View settings: View template settings H5P embed not rendered

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#157]
How to reproduce:

1) In the content bank add a H5P element (example accordion)
2) In the editor in the view template in the view settings, add the H5P via the H5P Editor Button
3) Save view
4) Result: a link to h5p is shown instead of the rendered H5P element

**Comment by dasistwas** [comment]
Maybe add format_text?

**Comment by michaelpollak** [comment]
Good morning David,
I just tested on mdl3.9, added texteditor field to a grid view.
Used the h5p button in the editor to upload an h5p file (https://h5p.org/arithmetic-quiz).
Embedding worked as expected, code in the contents table looks like this
`<div class="h5p-placeholder" contenteditable="false">@@PLUGINFILE@@/arithmetic-quiz-22-57860.h5p</div>`

Are you embedding from the moodle instance or from some other source? Is there a specific format you are embedding? Does the h5p work when the link is used?

**Comment by dasistwas** [comment]
@michaelpollak it is in view settings -> view template.

**Comment by michaelpollak** [comment]
Found the two bugs and patched them, works in my tests and should be fixed for you as well.
Thanks for the clarification, I missed that detail at first :)

**Comment by dasistwas** [comment]
hmmm. now the accordion is not displayed for role student, but for teacher it is displayed:

```
<div class="accordion" id="accordionExample">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Übersicht Finanzierungsbeiträge Gesamtsummen
        </button>
            </h5>
        </div>

        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                <pre>
asdf
as
df
asdf
as
fd
af
      </pre>
            </div>
        </div>
    </div>
</div>
<div>Die Summe aller Zahlungen muss folgendes ergeben: 500 * Anzahl der Quadratmeter.</div>
<div>Aktuelle Annahme für den Finanzierungsbeitrag: 500€/m2, Schwankungsbreite: 20%</div>
<div><br></div>
```

**Comment by dasistwas** [comment]
OK, that's not a datalynx issue. it happens also on a simple page in moodle. i have to find out why.

**Comment by michaelpollak** [comment]
If you want me to track down the issue just let me know :) Good luck.

**Comment by dasistwas** [comment]
works now. using h5p instead of the accordion code does the trick. so i am not going to look deeper into that issue. thank you for fixing the format_text problems
