### ISSUE TITLE
Check of select field usage does not work for "Auswahlbeschränkung"

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#158]
How to reproduce

1) Add a select field with setting: Auswahlbeschränkung -> 1 (That means the element can only be selected once. When selected in one entry it can not be selected for another entry anymore. Add 3 lines of selectable items in the setting
2) Add an entry select option 1 -> Save entry
3) Edit entry -> Save: Does not work, error " Sie können die 'Option 1' Option nicht nochmal auswählen, weil Sie die Höchstzahl der Auswahl dieser Option bereits erreicht haben. 

But it should be possible to edit the existing entry.

**Comment by michaelpollak** [comment]
Extended the function get_disabled_values_for_user() to accept the entryid of the currently validated input and exclude this from check. Smart fix with very little overhead, already tested and confirmed.

**Comment by dasistwas** [comment]
does not work. I can still select from dropdown even the option has already been selected elsewhere.

**Comment by dasistwas** [comment]
The limit is not user related. It is only depending on the selection for an entry: once selected for an entry it can not be chosen a 2nd time, if limit = 1

**Comment by michaelpollak** [comment]
Fixed, query is now datalynx instance wide and not user specific. Thanks for the feedback. :+1:

**Comment by dasistwas** [comment]
great fix, thank you
