### ISSUE TITLE
URGENT: Umbenennen / Hinzufügen von Feldoption im Feld  Select (multiple) führt zu Timeout

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#159]
Bei Instanzen mit vielen Einträgen und vielen Optionen im Feld  Select (multiple), kommt es zu einem Timeout, wenn ich eine Option hinzufüge bzw. eines umbenenne. Eventuell schlechte SQL Performance?

Anzahl der Einträge: 1597
Anzahl an Auswahloptionen: 60
Es gibt 2 Felder vom Type Select (multiple)

**Comment by dasistwas** [comment]
[20-Apr-2021 05:04:57 Europe/Vienna] PHP Fatal error:  Maximum execution time of 360 seconds exceeded in /srv/www/polak0002/htdocs/mod/datalynx/field/field_class.php on line 945

**Comment by michaelpollak** [comment]
I also have a problem deleting entries.
This dummyentry solution is not used, will test with all fields and remove :)
