### ISSUE TITLE
Adding data-* attribute in renderer does not work

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#164]
I want to add the following in the renderer's custom template:
```

<div class="col-1 vertical-container" data-phase="#value">
            <div class="vertical-text">#value</div>
</div>
```

But the data-phase attribute won't be saved.

**Comment by michaelpollak** [comment]
We are sanitising the html code on input using "PARAM_CLEANHTML" as modform parameter. So either we keep this and using data-phase attributes is impossible or we sanitise and validate at the output level. I feel like we are doing that and would use the moodle standard of PARAM_RAW. This is also discussed in the moodle libraries: https://github.com/moodle/moodle/blob/338b60f43b25c84e684dc075ff59132a24461d32/lib/moodlelib.php#L117

I'd propose removing the PARAM_CLEANHTML from all fields where we define renderers as it is probably used only by competent admins and teachers.

**Comment by dasistwas** [comment]
Yes user param_raw would be better. Thank you!

**Comment by dasistwas** [comment]
@michaelpollak already pushed the changes. Could you merge with your branch?

**Comment by michaelpollak** [comment]
Thanks :)
