### ISSUE TITLE
Error on new entry

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-mod_datalynx#165]
Notice: Undefined variable: paramsfoyui in /usr/www/users/wunder/fhb/mod/datalynx/classes/datalynx.php on line 527

**Comment by michaelpollak** [comment]
Can you give me some more info on how to reproduce? It is (luckily) not happening here :)

**Comment by dasistwas** [comment]
Here is a backup. Happens all the time there:
[backup-moodle2-course-3-mawm-bb-4-ss2020-eii2-20210628-1334.mbz.zip](https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/files/6725901/backup-moodle2-course-3-mawm-bb-4-ss2020-eii2-20210628-1334.mbz.zip)

**Comment by michaelpollak** [comment]
Damn typo I introduced six months ago, sorry for that :)

**Comment by dasistwas** [comment]
thanks, it's fixed
