### ISSUE TITLE
Possible Error with file storage  on 3.11

### ISSUE THREAD

**Issue by winnidat** [Wunderbyte-GmbH/moodle-mod_datalynx#175]
Workaround: https://moodle.org/mod/forum/discuss.php?d=423658

**Comment by dasistwas** [comment]
Ist das nicht vielleicht schon der Fix?
https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/commit/80075080339e7e7736904ee9c1020ccd3376647f

**Comment by winnidat** [comment]
ja schaut gut aus
