### ISSUE TITLE
Mandatory [[*required]] fields with tags not working?

### ISSUE THREAD

**Issue by goose2000** [Wunderbyte-GmbH/moodle-mod_datalynx#179]
I was reading the documentation on using ' * ' in front of tags to make them mandatory. I could not get this to work. No error, just the field would not render, just shown as text.

![Mandatory_screenshot-2022 11 15-08_31_21](https://user-images.githubusercontent.com/2395298/201933134-791b40db-3ae9-4737-b7de-55f8c5778fda.png)

**Comment by dasistwas** [comment]
That's the old way. The new way is to use field renderer and field behaviors in order to achieve that.

**Comment by dasistwas** [comment]
Manage -> Fields -> Behaviors. Then you add a "Required" behavior. Then you attach the behavior to a field in a view.

**Comment by goose2000** [comment]
Thanks David - it's very cool, with the pop-up menus in the entry view. Are date formats controlled by renderers? I could not get the Time field setting "Display format" to have any affect using:  %m/%d/%Y
