### ISSUE TITLE
Creating CSV view fails with implode error

### ISSUE THREAD

**Issue by jommoj** [Wunderbyte-GmbH/moodle-mod_datalynx#183]
Creating a CSV view fails with error message
implode(): Argument #1 ($pieces) must be of type array, string given
No CSV is created.

This happens on a fresh install of Datalynx in a Moodle 4 environment. Other views can be created and updated without any error messages. Tried in different instances, tried logging in and out, tried clearing caches, fields are available, other views are available.

Error message indicates usage of implode's legacy signature. The only suspicious call to implode can be found in [rule/rule_manager.php](https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/blob/3e59f1cdc2e642cb08e5fdb0521c05a873e13a37/rule/rule_manager.php#L279)

Do you have any hints? Thanks a lot!

**Comment by dasistwas** [comment]
Could you provide your PHP version? I assume it is 8.0 or 8.1. This might be related to stricter handling of type declarations. I will check that.

**Comment by jommoj** [comment]
Thanks a lot for your swift reply. I need to check the PHP version with the server admin, I don't have admin access to this installation. I will provide this asap.

And yes, I'm assuming 8.x as well, because the legacy signature was removed from 7.4 to 8.0. This is why I checked the usage of implode within your module's code. I also added rules in order to check, if non-existing rules might cause this error, but it still happens.

**Comment by dasistwas** [comment]
Fixed in https://github.com/Wunderbyte-GmbH/moodle-mod_datalynx/commit/332483a27f65202b3362f47a181ef195b14e8830

Workaround: First create fields, then create the view (makes mor sense)

**Comment by dasistwas** [comment]
You can get the new version at https://moodle.org/plugins/mod_datalynx/v3.0-dataintelligence/29825

**Comment by jommoj** [comment]
Thanks a lot for the immediate update!
I'm not sure, if the workaround will do the job.  I added fields first, created tabular, grid and pdf afterwards, then CSV creation fails. We will install the fix asap and let you know, if it resolves the issue.

**Comment by jommoj** [comment]
The issue is resolved, CSV is working as expected. Thanks a lot for your assistance!
