### ISSUE TITLE
Multiple submit buttons validation

### ISSUE THREAD

**Issue by michaelpollak** [Wunderbyte-GmbH/moodle-mod_datalynx#93]
We render a submit button array at the top and bottom of every form. 
Moodle adds ids by default in add_action_buttons(), these are duplicates.

Checked and noted that ids are not important to the submission process, so we override the function and add a parameter $multiple to allow to pass an iterator.

**Comment by michaelpollak** [comment]
I noticed that class changes when a button is named "cancel" it get the btn-secondary class, the button cancel_1 is btn-primary. Can't override this yet, reading up on the documentation. 

Other then that this solution validates fine.

**Comment by dasistwas** [comment]
You want to put this in review?

**Comment by michaelpollak** [comment]
A classic German "Jein", the multiple submit buttons are better now but not 100 %. The cancel button has an error string attached which still has a duplicate id "id_error_cancel". As it is not completely fixed I will keep this open for now. Thank you for checking it out!

**Comment by michaelpollak** [comment]
After working on this some more I give up. We can either ignore the little remaining validation error, remove one cancel button or remove the submit button line on top. What's your opinion? Thank you.

**Comment by dasistwas** [comment]
@michaelpollak What are the remaining issues? Phone call faster?

**Comment by michaelpollak** [comment]
Didn't reach you via phone,
validation complained about the two rows of submit buttons, one above and one below the entry.
I fixed it by renaming the second row with a postfix which worked fine. The only thing that is not validating is the div for errors created by moodle with the duplicate id "id_error_cancel". If I create a normal submit button I am able to rename it but the css classes are wrong and cannot be changed. So the cancel button looks like a submit and that's problematic.

**Comment by michaelpollak** [comment]
Your idea was a gamechanger, thank you David. The delegated buttons work like a charm and validation is finally perfect. Glad this is done :)

For future reference:
The second line of buttons have an onclick parameter that delegates their function to the original action buttons.

**Comment by dasistwas** [comment]
Yes, it's done.
